#!/bin/sh 
# Copyright (C) 2007-8 One Laptop Per Child Association, Inc.
# Licensed under the terms of the GNU GPL v2 or later; see COPYING for details.
# Written by C. Scott Ananian <cscott@laptop.org>
if="$1"
updown="$2"
if [[ "$updown" = "up" && -f /etc/xsce/openvpn_allowed ]]; then
  if [[ "$if" = "wlan0" && -f /etc/xsce/access_point ]]; then
    exit 0
  fi
  gateway=
  loop=1
  while [[ -z $gateway && $loop < 10 ]]; do
    gateway=`netstat -rn|grep UG|gawk '{print $2}'`
    sleep 1
    (( loop++ ))
  done
  if [ ! -z $gateway ]; then
   	ping -c 2  10.8.0.1
	  if [ $? -ne 0 ]; then
	    /usr/bin/systemctl restart openvpn@xscenet.service
    fi
  fi
fi
