#!/bin/bash
mkdir -p /opt/schoolserver/downloads
mkdir -p /etc/xsce
systemctl enable sshd.service
systemctl start sshd.service

ansible-playbook -i ansible_hosts xo1.yml --connection=local --extra-vars  "openvpn_enabled=True kiwix_serve_enabled=True"
