#!/bin/bash
mkdir -p /opt/schoolserver/downloads
mkdir -p /etc/xsce
systemctl enable sshd.service
systemctl start sshd.service

ansible-playbook -i ansible_hosts xo1.yml --connection=local -e openvpn_enabled=True kiwix_server_enabled=True
