#!/bin/bash -x
# Absolute path to this script.
shopt -s dotglob
SCRIPT=$(readlink -f $0)
# Absolute path this script is in.
SCRIPTPATH=`dirname $SCRIPT`
cd $SCRIPTPATH
cd ..
pwd
#/usr/bin/cp -Rf trees/1.5/* /
