#!/bin/bash -x
# Absolute path to this script.
shopt -s dotglob
SCRIPT=$(readlink -f $0)
# Absolute path this script is in.
SCRIPTPATH=`dirname $SCRIPT`
cd $SCRIPTPATH
cd ../trees/1.0
pwd
/usr/bin/cp -Rf * /
